version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'monday'
          time: '04:00'
          timezone: 'UTC'
      open-pull-requests-limit: 5
      commit-message:
          prefix: 'deps'
      ignore:
          - dependency-name: 'typescript'
            versions: ['>=5.5.0']
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'monday'
          time: '04:30'
          timezone: 'UTC'
      open-pull-requests-limit: 5
      commit-message:
          prefix: 'deps(actions)'
