@number_of_rows = 15 
@include_optional_fields = true
@include_headers = true
@has_invalid_rows = false

####
POST http://localhost:3001/api/generate
Content-Type: application/json
Accept: */*

{
    "fileType": "SDDirect",
    "includeHeaders": true,
    "includeOptionalFields": {{include_optional_fields}},
    "numberOfRows": {{number_of_rows}}
}

####

POST http://localhost:3001/api/generate
Content-Type: application/json
Accept: */*

{
    "fileType": "SDDirect",
    "includeHeaders": false,
    "includeOptionalFields": {{include_optional_fields}},
    "numberOfRows": {{number_of_rows}}
}

###
POST http://localhost:3001/api/generate
Content-Type: application/json
Accept: */*

{
    "fileType": "SDDirect",
    "includeHeaders": true,
    "includeOptionalFields": {{include_optional_fields}},
    "numberOfRows": {{number_of_rows}},
    "hasInvalidRows": true
}

####

POST http://localhost:3001/api/generate
Content-Type: application/json
Accept: */*

{
    "fileType": "SDDirect",
    "includeHeaders": false,
    "includeOptionalFields": {{include_optional_fields}},
    "numberOfRows": {{number_of_rows}},
    "hasInvalidRows": true
}