name: CI

on:
    push:
        branches: ['**']
    pull_request:
        branches: ['**']

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-test:
        name: Node ${{ matrix.node }} • ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                node: [22.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
                  cache: 'npm'

            - name: Install
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build

            - name: Test (with coverage)
              run: npm run test:coverage

            - name: Upload coverage artifact
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-${{ matrix.os }}-node${{ matrix.node }}
                  path: coverage/
                  if-no-files-found: ignore

            - name: Job summary
              if: always()
              run: |
                  echo "### CI Summary" >> $GITHUB_STEP_SUMMARY
                  echo "- OS: ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
                  echo "- Node: ${{ matrix.node }}" >> $GITHUB_STEP_SUMMARY
                  echo "- Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
