name: Security Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 4 * * 1'

permissions:
  contents: read

jobs:
  npm-audit:
    name: npm audit (high and critical)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - name: Audit for high/critical vulnerabilities
        run: |
          npm audit --audit-level=high
